version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: soal_postgres
    environment:
      POSTGRES_USER: soal
      POSTGRES_PASSWORD: soalpass
      POSTGRES_DB: soaldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: soal_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
